name: Zona Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"  # Executar a cada 3 horas
  workflow_dispatch:  # Permite disparar o workflow manualmente

jobs:
  deploy-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        API_URL: ${{ secrets.API_URL }}
      run: |
        python bot.py &
        BOT_PID=$!                     # Salva o PID do processo
        echo "Bot iniciado com PID $BOT_PID"
        sleep 10800                    # Aguarda 3 horas (3 * 60 * 60 segundos)
        echo "Encerrando o bot..."
        kill $BOT_PID                  # Finaliza o processo do bot