name: Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Token do bot no Telegram
      run: python bot.py
